seo:
  site_name: The Sleep Co
  title: Default SEO Title
  description:
  keywords:
  social_image:
  author:
  favicon_image:
social:
  instagram_username:
  facebook_url:
  twitter_username:
design:
  featured-text_color: '#F4B525'
  white-text_color: 'white'
  navy-text_color: '#192B37'

