seo:
  site_name: The Sleep Co
  title: Default SEO Title
  description:
  keywords:
  social_image:
  author:
  favicon_image:
social:
  instagram_username:
  facebook_url:
  twitter_username:
design:
  featured_color: '#f4b525'
  white_color: '#ffffff'
  dark_color: '#192b37'
  light_color: '#E3ECF2'
  subtitle_color: 'rgb(120,120,125)'
  quote_color: 'rgb(120,120,125)'
  active-gallery_color: 'rgb(20,20,20)'
  active-gallery-subtitle_color: 'rgba(20,20,20,0.95)'
