seo:
  site_name: The Sleep Co
  title: Default SEO Title
  description:
  keywords:
  social_image:
  author:
  favicon_image:
social:
  instagram_username:
  facebook_url:
  twitter_username:
design:
  featured-text: '#192B37'
  white-text: 'white'
  navy-text: '#192B37'

